---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: how2die/buildserver
        env:
        - name: DOCKER_USER_ID
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: password
        - name: DOCKER_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: registry
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 50000
          name: jnlp-port
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: docker-daemon-socket
            mountPath: /var/run
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: docker-daemon-socket
          hostPath:
            path: /var/run/dind/
