# Docker in Docker (see https://github.com/jupyterhub/binderhub/issues/328#issuecomment-350193630)
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dind
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
        - dockerd
        - --storage-driver=overlay2
        - -H unix:///var/run/dind/docker.sock
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/lib/docker
          - name: docker-daemon-socket
            mountPath: /var/run/dind
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-graph-storage
        emptyDir: {}
      - name: docker-daemon-socket
        hostPath:
          path: /var/run/dind/
